name: Server Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: "adopt"

    - name: Docker build & push to docker repo
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker buildx build --platform linux/amd64 -t johoon/playground-backend:latest --push .

    - name: Deploy to instance
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull johoon/playground-backend:latest
          docker-compose up -d
          docker image prune -f
